export default [
  { id: 1, 
    departure: "Lagos",
     destination: "Abuja",
     date: "",
      time: "2:00 PM",
      price: 36421, 
      airline: "JoyAir" },

  { id: 2, 
    departure: "Lagos", 
    destination: "Port-Harcourt",
     date: "",
      time: "9:15 AM",
      price: 43577, 
      airline: "JoyAir" },
      
  { id: 3, departure: "Lagos", destination: "Ibadan", date: "", time: "6:15 PM", price: 76230, airline: "JoyAir" },
  { id: 4, departure: "Lagos", destination: "Enugu", date: "", time: "6:15 PM", price: 76895, airline: "JoyAir" },
  { id: 5, departure: "Lagos", destination: "Kano", date: "", time: "7:30 AM", price: 55618, airline: "JoyAir" },
  { id: 6, departure: "Abuja", destination: "Lagos", date: "", time: "12:00 PM", price: 43389, airline: "JoyAir" },
  { id: 7, departure: "Abuja", destination: "Port-Harcourt", date: "", time: "4:00 PM", price: 30747, airline: "JoyAir" },
  { id: 8, departure: "Abuja", destination: "Ibadan", date: "", time: "8:00 AM", price: 65093, airline: "JoyAir" },
  { id: 9, departure: "Abuja", destination: "Enugu", date: "", time: "9:00 AM", price: 32864, airline: "JoyAir" },
  { id: 10, departure: "Abuja", destination: "Kano", date: "", time: "10:15 AM", price: 68302, airline: "JoyAir" },
  { id: 11, departure: "Port-Harcourt", destination: "Lagos", date: "", time: "8:30 AM", price: 45585, airline: "JoyAir" },
  { id: 12, departure: "Port-Harcourt", destination: "Abuja", date: "", time: "1:30 PM", price: 59131, airline: "JoyAir" },
  { id: 13, departure: "Port-Harcourt", destination: "Ibadan", date: "", time: "3:00 PM", price: 64697, airline: "JoyAir" },
  { id: 14, departure: "Port-Harcourt", destination: "Enugu", date: "", time: "7:15 AM", price: 59139, airline: "JoyAir" },
  { id: 15, departure: "Port-Harcourt", destination: "Kano", date: "", time: "5:15 PM", price: 34541, airline: "JoyAir" },
  { id: 16, departure: "Ibadan", destination: "Lagos", date: "", time: "1:30 PM", price: 78841, airline: "JoyAir" },
  { id: 17, departure: "Ibadan", destination: "Abuja", date: "", time: "3:00 PM", price: 71883, airline: "JoyAir" },
  { id: 18, departure: "Ibadan", destination: "Port-Harcourt", date: "", time: "11:00 AM", price: 73293, airline: "JoyAir" },
  { id: 19, departure: "Ibadan", destination: "Enugu", date: "", time: "7:45 PM", price: 61536, airline: "JoyAir" },
  { id: 20, departure: "Ibadan", destination: "Kano", date: "", time: "8:00 AM", price: 64234, airline: "JoyAir" },
  { id: 21, departure: "Enugu", destination: "Lagos", date: "", time: "3:45 PM", price: 55999, airline: "JoyAir" },
  { id: 22, departure: "Enugu", destination: "Abuja", date: "", time: "2:30 PM", price: 56512, airline: "JoyAir" },
  { id: 23, departure: "Enugu", destination: "Port-Harcourt", date: "", time: "6:00 AM", price: 63394, airline: "JoyAir" },
  { id: 24, departure: "Enugu", destination: "Ibadan", date: "", time: "4:00 PM", price: 66543, airline: "JoyAir" },
  { id: 25, departure: "Enugu", destination: "Kano", date: "", time: "6:30 AM", price: 55269, airline: "JoyAir" },
  { id: 26, departure: "Kano", destination: "Lagos", date: "", time: "9:30 AM", price: 61540, airline: "JoyAir" },
  { id: 27, departure: "Kano", destination: "Abuja", date: "", time: "7:00 AM", price: 71320, airline: "JoyAir" },
  { id: 28, departure: "Kano", destination: "Port-Harcourt", date: "", time: "12:15 PM", price: 68155, airline: "JoyAir" },
  { id: 29, departure: "Kano", destination: "Ibadan", date: "", time: "8:15 AM", price: 48770, airline: "JoyAir" },
  { id: 30, departure: "Kano", destination: "Enugu", date: "", time: "6:00 PM", price: 71332, airline: "JoyAir" }
];
